apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: root
  namespace: argo
spec:
  generators: []
  template:
    metadata:
      name: 'nginx-local'
    spec:
      project: default
      source:
        repoURL: https://github.com/zralt/k8s-argocd.git
        targetRevision: HEAD
        path: apps/
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: nginx-localchart
