apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: root
  namespace: argo
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          env: dev
  - list:
      elements:
      - appName: nginx
        appNamespace: nginx-localchart
      - appName: apache
        appNamespace: apache-localchart
  template:
    metadata:
      name: '{{ appName }}'
    spec:
      project: default
      source:
        repoURL: https://github.com/zralt/k8s-argocd.git
        targetRevision: HEAD
        path: 'apps/{{ appName }}'
        helm:
          valueFiles:
            - values-prod.yaml
      destination:
        server: '{{ name }}'
        namespace: '{{ appNamespace }}'
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
