apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: root
  namespace: argo
spec:
  generators:
  - list:
      elements:
      - app: nginx
        app_ns: nginx-localchart
      - app: apache
        app_ns: apache-localchart
  template:
    metadata:
      name: '{{ app }}-local'
    spec:
      project: default
      source:
        repoURL: https://github.com/zralt/k8s-argocd.git
        targetRevision: HEAD
        path: 'apps/{{ app }}'
        helm:
          valueFiles:
            - values-prod.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ app_ns }}'
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
